import json, sys
S = sys.argv[1]; out = sys.argv[2]
LB = 0.45359237
# ISO 4000 / ETRTO load index -> kg (only the range used here)
LI = {100:800,101:825,102:850,103:875,104:900,105:925,106:950,107:975,108:1000,109:1030,110:1060,111:1090,112:1120,113:1150,114:1180,115:1215,116:1250,117:1285,118:1320,119:1360,120:1400,121:1450,122:1500,123:1550,124:1600,125:1650}
sl = json.load(open(f"{S}/etrto_sl.json")); xl = json.load(open(f"{S}/etrto_xl.json"))
# LI 118 sits above the column header on page 35, so the parser misses it; typed from the page (checked against the rendered page).
sl["118"] = [1929,2039,2093,2138,2238,2300,2337,2436,2535,2569,2623,2723,2766,2822,2910]
problems = []
def check_rows(name, d, lis):
    rows = {}
    for li in lis:
        r = d.get(str(li))
        if not r: problems.append(f"{name} {li} missing"); continue
        if r != sorted(r): problems.append(f"{name} {li} not increasing")
        if abs(r[-1] - LI[li] / LB) > 3: problems.append(f"{name} {li} top {r[-1]} vs LI {LI[li]/LB:.0f}")
        rows[li] = r
    return rows
slrows = check_rows("SL", sl, range(100, 126))
xlrows = check_rows("XL", xl, range(109, 121))
lt = {}
for r in json.load(open(f"{S}/lt.json")):
    if r["fit"] != "Single": continue
    for g in r["ranges"]:
        lb = dict(r["loads"]).get(g["maxPsi"])
        if abs(lb - LI[int(g["li"])] / LB) > 3: problems.append(f"{r['size']} {g} load {lb}")
    lt[r["size"]] = {"single": r["loads"], "ranges": [{"range": g["range"], "maxPsi": g["maxPsi"], "li": int(g["li"])} for g in r["ranges"]]}
fl = {}
for r in json.load(open(f"{S}/fl.json")):
    for g in r["ranges"]:
        lb = dict(r["loads"]).get(g["maxPsi"])
        if abs(lb - LI[int(g["li"])] / LB) > 3: problems.append(f"{r['size']} {g} load {lb}")
    fl[r["size"]] = {"single": r["loads"], "ranges": [{"range": g["range"], "maxPsi": g["maxPsi"], "li": int(g["li"])} for g in r["ranges"]]}
if problems:
    print("\n".join(problems)); sys.exit(1)
def rows_js(rows):
    return "\n".join(f"        {li}: [{', '.join(map(str, v))}]," for li, v in rows.items())
def pts(p): return ", ".join(f"[{a}, {b}]" for a, b in p)
def sizes_js(d):
    o = []
    for size, v in d.items():
        rg = ", ".join(f'{{ range: "{g["range"]}", maxPsi: {g["maxPsi"]}, li: {g["li"]} }}' for g in v["ranges"])
        o.append(f'      "{size}": {{\n        single: [{pts(v["single"])}],\n        ranges: [{rg}],\n      }},')
    return "\n".join(o)
js = f'''/*
 * tables.js: tyre load/inflation tables, as published. GENERATED by
 * scripts/gen_tables.py from the Toyo guide (source "toyo2020"), then each
 * row was checked by eye against the rendered PDF page and by script: every
 * row rises with pressure, and the load at each row's top pressure equals the
 * load index's rated load. Don't hand-edit: regenerate or re-check instead.
 *
 * Loads are in pounds (lb) per tyre and pressures in psi, exactly as the
 * source prints them; calc.js converts. Single-fitment loads only (no duals).
 */
(function (root) {{
  "use strict";

  root.TYRE_TABLES = {{
    // ISO 4000 / ETRTO load index -> rated load (kg), for the indices used here.
    loadIndexKg: {{ {", ".join(f"{k}: {v}" for k, v in LI.items())} }},

    // ETRTO passenger-car tyres (ISO metric sizes such as 265/65R17 112T).
    // Load depends only on the load index and pressure.
    "etrto-sl": {{
      label: "ETRTO Standard Load",
      source: "toyo2020",
      where: "Toyo guide pp. 34-35, reproducing the ETRTO Standards Manual 2005",
      psi: [{", ".join(map(str, sl["_psi"]))}],
      rowsLb: {{
{rows_js(slrows)}
      }},
    }},
    "etrto-xl": {{
      label: "ETRTO Reinforced / Extra Load (XL)",
      source: "toyo2020",
      where: "Toyo guide pp. 36-37, reproducing the ETRTO Standards Manual 2005",
      psi: [{", ".join(map(str, xl["_psi"]))}],
      rowsLb: {{
{rows_js(xlrows)}
      }},
    }},

    // TRA light-truck (LT-metric) tyres: one load curve per size; the load
    // range (C/D/E) only sets how high the pressure (and load) may go.
    "tra-lt": {{
      label: "TRA Light Truck (LT-metric)",
      source: "toyo2020",
      where: "Toyo guide pp. 24-27 (TRA Light Truck Load & Inflation Table)",
      sizes: {{
{sizes_js(lt)}
      }},
    }},
    "tra-flotation": {{
      label: "TRA Flotation (LT)",
      source: "toyo2020",
      where: "Toyo guide p. 31 (TRA Flotation Table)",
      sizes: {{
{sizes_js(fl)}
      }},
    }},

    // Michelin's own table for one tyre: X Force S 7.50R16 116/114N.
    // Published as load per AXLE in kg (two tyres, single fitment).
    "michelin-750r16": {{
      label: "Michelin X Force S 7.50R16 116/114N",
      source: "michelinXForceS",
      where: "Michelin Australia product page, load & pressure table dated December 2020",
      axleKg: [[36, 1300], [40, 1400], [44, 1500], [47, 1600], [51, 1700], [54, 1800], [58, 1900], [62, 2000], [65, 2100], [69, 2200], [73, 2300], [76, 2400], [80, 2500]],
    }},
  }};
}})(typeof window !== "undefined" ? window : globalThis);
'''
open(out, "w", newline="\n").write(js)
print("ok", len(slrows), len(xlrows), list(lt), list(fl))
